language: cpp

compiler:
  - gcc
  - clang

os: linux

dist: bionic

sudo: required

branches:
  only:
    - master

notifications:
  slack:
    rooms:
      - ecpsparsesolvers:nBWC0jcAd7B1j9whHUYcaVJO
    on_failure: always
    on_success: change

env:
  matrix:
  - TEST_NUMBER=1 FILE="test_HSS_seq"
  - TEST_NUMBER=2 FILE="test_HSS_mpi"
  - TEST_NUMBER=3 FILE="test_sparse_seq"
  - TEST_NUMBER=4 FILE="test_sparse_mpi"

git:
  depth: 1

addons:
  apt:
    packages:
      # - g++
      # - gcc
      - gfortran
      - libblas-dev
      - liblapack-dev
      - libopenblas-dev
      - libmetis-dev
      - libscalapack-openmpi-dev
      - libparmetis-dev

before_install:
  - mkdir installDir
  # - test -n $CC && unset CC

install:
  # - printf "Installing openmpi\n"
  # - sudo apt-get install openmpi-bin libopenmpi-dev
  # - printf "Done installing openmpi\n"

  # - printf "Installing scalapack, parmetis\n"
  # - sudo apt-get install libscalapack-openmpi-dev libparmetis-dev
  # - printf "Done installing scalapack, parmetis\n"

  - cd $TRAVIS_BUILD_DIR/installDir
  - wget --no-check-certificate https://gforge.inria.fr/frs/download.php/file/34618/scotch_6.0.4.tar.gz
  - tar -xf scotch_6.0.4.tar.gz
  - cd ./scotch_6.0.4
  - export SCOTCH_DIR=`pwd`/install
  - mkdir install
  - cd ./src
  - cp ./Make.inc/Makefile.inc.x86-64_pc_linux2 Makefile.inc
  - sed -i "s/-DSCOTCH_PTHREAD//" Makefile.inc
  - sed -i "s/CCD/#CCD/" Makefile.inc
  - printf "CCD = mpicc\n" >> Makefile.inc
  - cat Makefile.inc
  - make ptscotch > make_scotch.log 2>&1
  - make prefix=../install install > make_scotch_install.log 2>&1

  - cd $TRAVIS_BUILD_DIR
  - mkdir build
  - cd build
  - mpic++ --version
  - ls -alh /etc/alternatives/mpic++
  - |
    cmake .. \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=. \
    -DTPL_SCALAPACK_LIBRARIES="/usr/lib/x86_64-linux-gnu/libscalapack-openmpi.so"
  - make VERBOSE=1
  - make install
  - make tests

script:
  - cd $TRAVIS_BUILD_DIR
  - ./.travis_tests.sh
